version: "3.8"
services:
 
  postgresdb:
    image: "postgres"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
    ports:
        - "5432:5432"
