-- POSTGRES
ALTER TABLE employer
ALTER COLUMN yearly_revenue SET DATA TYPE FLOAT

ALTER TABLE conversation
ALTER COLUMN createdAt 
SET DEFAULT CURRENT_TIMESTAMP;

-- MYSQL
ALTER TABLE employer
MODIFY COLUMN yearly_revenue FLOAT(5,2);

ALTER TABLE conversation 
MODIFY COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;